### ISSUE TITLE
Cumulative explained variance plot (Scree plot) starting from 0 instead of 1

### ISSUE THREAD

**Issue by camilogarciabotero** [erdogant/pca#1]
Hi @erdogant,

I have been looking for a while for a good Python library that makes all PCA plots beautiful and I think your package achieves this goal by far. 

On the other hand while using your package I noticed that the Explained variance plot is starting from 0 (like normal Python indexes) and because of that I think it might be erasing the "last component" when generating the plot, moreover the "0" component is always starting from 0 which is not the common case for the Scree plot: 

![Screen Shot 2020-04-28 at 5 21 37 PM](https://user-images.githubusercontent.com/25586362/80543867-6e202200-8975-11ea-8518-f5249a6dee63.png)

If I wasn't clear enough with the issue, I'll be glad to answer your questions.
Cheers,
Camilo.

**Comment by erdogant** [comment]
Thanks Camilo!
Yes, totally.

**Comment by erdogant** [comment]
I provided a fix for the plot.
Please update with: pip install -U pca
