### ISSUE TITLE
Fit_transform but no transform()

### ISSUE THREAD

**Issue by M-Harrington** [erdogant/pca#11]
Hi, maybe I've missed it, but could you add a `transform` method to supplement `fit_transform`?  Ideally I'd like to call this on new data after it's already been fit and return PCs without refitting.

**Comment by erdogant** [comment]
The fitted model is stored in results and with the model it is possible to do the transformation step. However, I agree that it may be a bit inconvenient. So I created a transform function!

```
pip install -U distfit
import distfit
print(distfit.__version__)
```
The version should be >= 1.4.0

An example can be found in the readme!

**Comment by M-Harrington** [comment]
Thank you for the resource, and thank you for authoring the package! It’s
great and has a lot more useful functionality than the sole arm package!

Cheers
