### ISSUE TITLE
Enable transparency alpha?

### ISSUE THREAD

**Issue by nightvision04** [erdogant/pca#13]
Would you be comfortable if we added transparency alpha for the samples? I use your library for lots of stuff at work with particularly dense datasets. I was thinking something like:

 `model.biplot(...transparecy_alpha=0.2)`

Anyhow, let me know if you would like a pull request for it.

**Comment by erdogant** [comment]
That would be great!

**Comment by nightvision04** [comment]
Added a pull request. Once the tests complete and are successful, I'll close this issue.

**Comment by erdogant** [comment]
Thanks again and I created a new pip install version!
https://github.com/erdogant/pca/releases/tag/1.5.0

` pip install -U pca `
