### ISSUE TITLE
How do change the biplot (PC1 and PC2) to other components (like PC1 and PC3 or PC4)?

### ISSUE THREAD

**Issue by Oceansponge** [erdogant/pca#20]

**Comment by erdogant** [comment]
Thanks for the question. I included PC as an extra parameter in biplot now. 

Update with: 

pip install -U pca

```
fig, ax = model.biplot(PC=[0, 1])
fig, ax = model.biplot3d(PC=[0, 1, 2])

```

**Comment by Oceansponge** [comment]
Dear Erdigant,

Thanks a lot for your update. That's really helpful. 

I updated the pca package as your suggestion. When I call the biplot function (fig,ax = model.biplot(PC = [1, 2]), the arrows for PC2 and PC3 are identical to the ones for PC1 and PC2 (fig,ax = model.biplot(PC = [0, 1]). Could you please double check the code  between line 635 and line 679? Some of the variables in the def biplot may need to be updated accordingly (such as mean_x, mean_y, xarrow, yarrow).

Looking forward to your further update. 

Many thanks and kind regardly,
Shuzhuang

**Comment by erdogant** [comment]
You are right! I will look into it

**Comment by erdogant** [comment]
I created some fixes. Can you check it?

`pip install -U pca
`

**Comment by Oceansponge** [comment]
Perfect! Many thanks for your updates.
