### ISSUE TITLE
about the loading plot and score plot

### ISSUE THREAD

**Issue by weiping2020** [erdogant/pca#23]
hi，
could you please tell how to do the loading plot by PCA library?
and what is the different between loading plot and score plot?

**Comment by erdogant** [comment]
The loadingplot is named the biplot. You can find more information on the [documentation pages](https://erdogant.github.io/pca/pages/html/Algorithm.html#examination-of-the-loadings)

The [blog](https://towardsdatascience.com/what-are-pca-loadings-and-biplots-9a7897f2e559) can also be interesting to read where I describe more about the interpretation of the loadings with the biplot and and the scree-plot.

**Comment by weiping2020** [comment]
thanks erdogant, I have plotted the loading plot, it has loading points and scatter points, so how to delete the scatter points( initial points) ?  just show the loading arrows

**Comment by erdogant** [comment]
See (here)[https://erdogant.github.io/pca/pages/html/Plots.html#biplot]

`model.biplot(cmap=None, label=False, legend=False)`

**Comment by erdogant** [comment]
re-open the issue if it was not clear.
