### ISSUE TITLE
Issues with 2 principal components

### ISSUE THREAD

**Issue by acmoudleysa** [erdogant/pca#25]
![image](https://user-images.githubusercontent.com/109609332/179778447-4b280c4a-39cc-448d-ab05-5339b990ed31.png)

How do I fix this?

**Comment by erdogant** [comment]
The first component seems to explains 96% of all variation in your data. The second 4%. Thus all features that are horizontal-ish have the most weight. Did you normalize the data? Maybe that can help. Alternatively, Have you checked whether you have highly correlated features? You can try to remove the multicollinearity at start and then re-run the analysis. You can also limit the number of loadings but that is only for visualization purposes.
