### ISSUE TITLE
How to fix the head of the arrows in biplot?

### ISSUE THREAD

**Issue by tomasdelvechio** [erdogant/pca#28]
When I run this code

```python
fig,ax=cl.pca.biplot(n_feat=2, y=df_labels.label_names, legend = True)
```

I get the next image 

![download](https://user-images.githubusercontent.com/1976584/188339758-52fb23f1-389e-44db-b5bb-536355214281.png)

How to fix the arrowshead width or length?

**Comment by erdogant** [comment]
oh wow, what happend. That's what we call a big arrowhead.

**Comment by erdogant** [comment]
I created a new version that should fix this issue. 
Update to the latest version:

`pip install -U pca
`

**Comment by tomasdelvechio** [comment]
Great! The biplot now showing fine.

![index](https://user-images.githubusercontent.com/1976584/188751359-e5889905-34a5-4320-8b4a-9712184033c7.png)

Thanks for the fix
