### ISSUE TITLE
Question: `n_components` in documentations?

### ISSUE THREAD

**Issue by BrandonKMLee** [erdogant/pca#30]
In https://erdogant.github.io/pca/pages/html/pca.pca.html
It says `pca.pca.pca(n_components=0.95, n_feat=25, method='pca', alpha=0.05, n_std=2, onehot=False, normalize=False, detect_outliers=['ht2', 'spe'], random_state=None, verbose=3)`
`n_components` is not an integer like `hotellingsT2` but instead something similar to `alpha`, but neither is documented on how these two are used.

**Comment by erdogant** [comment]
Thank you for pointing this out! The docstrings were accidentally placed at a part that is not visible when generating the documentation pages. 

See update [here](https://erdogant.github.io/pca/pages/html/pca.pca.html).
