### ISSUE TITLE
Overlapping annotations / text in the biplot() function

### ISSUE THREAD

**Issue by rejusam** [erdogant/pca#33]
When we create a biplot with the biplot() function, the labels of the variable names overlap for the variables with the same eigenvector. An example of this can be found below:
[https://drive.google.com/file/d/1OuzXq1NvLU3qBknbmdi0kzPvheZwt_Aq/view?usp=share_link](https://drive.google.com/file/d/1OuzXq1NvLU3qBknbmdi0kzPvheZwt_Aq/view?usp=share_link)

**Comment by erdogant** [comment]
I created an update where I incorporated the `adjust_text` library to prevent overlapping annotations in the biplot.
Please update to the latest version >= v1.8.4.

`pip install -U pca`

Can you check whether this solves your issue?

**Comment by rejusam** [comment]
Awesome! Perfect! Thank you!
