### ISSUE TITLE
title field in CITATION.cff contains description

### ISSUE THREAD

**Issue by fmatter** [erdogant/pca#35]
Is this on purpose? I.e., do you want `pca` to be cited as having the title *pca is a python package that performs the principal component analysis and makes insightful plots.*?

**Comment by fmatter** [comment]
1) I would definitely include the name of the package

2) the definite article *the* implies that this is the only python package for this job, is that intentional?

If not, I would go with something like "pca: a python package for principal component analysis"

**Comment by erdogant** [comment]
Not intentional. I like your suggestion better.

**Comment by fmatter** [comment]
Looks very citeable now! :)
