### ISSUE TITLE
Unable turn off the default plot title of `biplot()`.

### ISSUE THREAD

**Issue by rejusam** [erdogant/pca#37]
How do I remove the default plot title of `biplot()`?
I tried using the `title` parameter of the `biplot()` function, but I'm still unable to remove the default plot title.
`fig, ax = model.biplot(label=True, legend=False, cmap = 'autumn', figsize=(15,10), title= None)`
I also tried to modify the returned axis of `biplot()`:
`ax.set_title(' ', loc='center')`
but it is not modifying the title.

**Comment by erdogant** [comment]
I see why this is confusing. The idea was as follows:

```
        title : str, default: None
            None: Automatically create title text based on results.
            '' : Remove all title text.
            'title text' : Add custom title text.

```
I updated the docstrings. I am open for alternative solutions.

**Comment by rejusam** [comment]
Thank You @erdogant
