### ISSUE TITLE
Feature request: use helper function approach for plotting

### ISSUE THREAD

**Issue by koutoftimer** [erdogant/pca#39]
# Problem

The only way to nest figures is via helper function as stated in [Matplotlib Quickstart](https://matplotlib.org/stable/tutorials/introductory/quick_start.html#making-a-helper-functions).

Current implementation requires monkey patching matplotlib before binplot call if one would like to have several subplots on the figure.

# Workaround

```python
@contextmanager
def monkey_patched_figure_and_subplot(fig: plt.Figure, ax: plt.Axes):
    old_figure = plt.figure
    old_add_subplot = fig.add_subplot

    def new_figure(*args, **kwargs):
        return fig

    def new_add_subplot(*args, **kwargs):
        return ax

    plt.figure = new_figure
    fig.add_subplot = new_add_subplot

    yield

    plt.figure = old_figure
    fig.add_subplot = old_add_subplot

...

model = pca(n_components=2)
model.fit_transform(data)
with monkey_patched_figure_and_subplot(fig, ax):
    model.biplot()
```

# Suggestion

Allow to pass `ax` and `fig` to `binplot` and other methods.

**Comment by tacaswell** [comment]
Adding the ability to pass an `Axes` into `biplot` may be simpler to implement and use.

**Comment by erdogant** [comment]
True. Please send a pull request or otherwise I will look into it but it may take some time.

**Comment by erdogant** [comment]
I implemented an optional parameter for `fig`. 
Before releasing, do you want to give it a try whether it works as expected?
You can install from github source as following (version should be 1.8.6):

`pip install git+https://github.com/erdogant/pca
`
```
from sklearn.datasets import make_friedman1
X, _ = make_friedman1(n_samples=200, n_features=30, random_state=0)

# Init
model = pca()

# Fit
model.fit_transform(X)

# Make plot with some parameters
fig, ax = model.biplot(fontdict={'size':10, 'weight':'normal'}, title=None, SPE=False, hotellingt2=True, n_feat=10, visible=False)

# Use the existing fig and create new edits such as different fontsize and title and SPE=True
fig, ax = model.biplot(fontdict={'size':16, 'weight':'bold'}, SPE=True, n_feat=3, fig=fig, visible=True, title='updated fig.')

```

**Comment by erdogant** [comment]
I created updates to add fig as input parameter to the biplot. [Here](https://erdogant.github.io/pca/pages/html/Examples.html#colors-in-plots) is an example.

Update to the latest version with:
`pip install -U pca`

**Comment by erdogant** [comment]
closing this one. Let me know if something is still missing.
