### ISSUE TITLE
Feature: Add loadings scale on secondary axes

### ISSUE THREAD

**Issue by Rendiere** [erdogant/pca#4]
When visualising bi-plots, it's often useful to interpret the loadings placed on each feature in order to make deductions such as "principle component 1 places approximately double the loading on features A,B & C than it places on feature D". 

Without the scale of the loading vectors in each principle component direction explicitly known however, this can lead to misleading deductions. 

_This feature request is thus to add the loading scales to each principle component axis._

**Example of biplot with loading scales shown**:

![image](https://user-images.githubusercontent.com/14853356/86594586-917bd480-bf97-11ea-9697-d2b881b10702.png)

**Comment by erdogant** [comment]
I agree and added the loading information to the plot.
update with:

`pip install -U pca
`
The new version should be >= 1.0.8
```
import pca
print(pca.__version__)
```
