### ISSUE TITLE
customizing marker shape

### ISSUE THREAD

**Issue by HeldLab** [erdogant/pca#42]
Really nice, easy to use package. Thanks for putting it together!

I did want to ask if it was possible to bring a second column of annotations (in addition to the 'y' you use as convention), in order to customize the marker shape. I suspect not based on the API, but it would be a great enhancement in the future.

Cheers,
Jason

**Comment by erdogant** [comment]
Thank you. I added the functionality! Update with `pip install -U pca`
In case you are wondering how you can thank me for this great new functionality, I love coffee ;-)

<a href='https://www.buymeacoffee.com/erdogant' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://cdn.ko-fi.com/cdn/kofi1.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>

**Comment by HeldLab** [comment]
Is it possible to encode the marker shape using strings instead of numbers? For example if the results are coming from 2 datasets, and you want to have a shape for each dataset and in a legend label one shape "dataset A" and the other "dataset B"?

Cheers,
Jason

**Comment by erdogant** [comment]
Yes. I entirely rewritten the plotting functionalties and includes this function too!
update to the latest version with: `pip install -U pca`
More information can be found [here](https://erdogant.github.io/pca/pages/html/Plots.html#control-color-marker-size-per-sample)

**Comment by erdogant** [comment]
I am closing this one as the functionality is created.
