### ISSUE TITLE
How to remove text labels from scatterplots?

### ISSUE THREAD

**Issue by wmsheer** [erdogant/pca#43]
Hi,

Thanks for the great package. Whenever I plot my data with the scatter() function, I get large text labels on each point. I'd like to remove these, but if I use any of the "fontcolor", "fontsize", or "fontweight" arguments, I get a TypeError stating "scatter() got an unexpected keyword argument 'fontcolor'" or the like. Do you know what may be happening?

Thanks!

**Comment by erdogant** [comment]
test labels can be removed with the font size:

```
# Remove text in scatter
fig, ax = model.biplot(fontsize=0, visible=True)
# Remove text in arrow
fig, ax = model.biplot(arrowdict={'fontsize': 0})
# # Remove both
fig, ax = model.biplot(fontsize=0, arrowdict={'fontsize': 0})


```

**Comment by erdogant** [comment]
closing this one.
