### ISSUE TITLE
What is the purpose of calling fig.set_visible(visible)?

### ISSUE THREAD

**Issue by normanius** [erdogant/pca#46]
I like this package a lot, thanks for the work!

Often, users wish to adjust the appearance of plots before displaying it. When model.biplot() is called, one can suppress the call to plt.show() by setting the argument `visible=False`. However, this also sets `fig.set_visible(False)`. In my Python / IPython environment, this has the side-effect that a later call to `plt.show()` will just show an empty figure, see below.

<img width="400" alt="image" src="https://github.com/erdogant/pca/assets/11406002/54344f64-ae53-4377-8385-cb89e8018273">

Setting the visible-status of the figure is not particularly user-friendly. I had to dig through this package's code to understand why the figure is not shown properly. For me, only the following works:

```python
fig, ax = model.biplot(n_feat=4, visible=False)
ax.axis("scaled")  # Some user adjustment...
fig.set_visible(True) # Required, otherwise the figure will be empty!
fig.show()
```

The question: What's the purpose of the call to fig.set_visible()? I recommend omitting this in [pca.py](https://github.com/erdogant/pca/blob/master/pca/pca.py) (I've counted two occurrences). 

Another thing one might want to consider: don't call plt.show() in plotting routines! That's often left to the users in other plotting packages. Personally, I find it intrusive when a package determines the time when a window appears in my scripts 😉

**Comment by erdogant** [comment]
I am not sure whether I understand what the best way would be to fix this based on your suggestion. The reason for suppressing the figure is that sometimes you do need to see the figure but just need to save it to disk or so.

I can remove the `fig.set_visible(visible)` and use the `plt.show(visible=visible)` if it leads to no issues with Ipython. Is that what you are saying?

**Comment by normanius** [comment]
Does [`plt.show()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html) take an argument `visible`? 

If you want to call plt.show() for the user, I would do it like this:

```python
if visible:
    fig.show()
```

But why calling plt.show() at all inside PCA methods?

In [this seaborn example](https://seaborn.pydata.org/examples/anscombes_quartet.html), one need to explicitly call plt.show() to make the plot show. Here, the user controls when the figure is shown, if at all. The user can also control later, if a figure is shown or not by setting fig.set_visible(False)...

See [this note](https://seaborn.pydata.org/faq.html#why-aren-t-my-plots-showing-up) from Michael Waskom on this matter.

See also [this SO thread](https://stackoverflow.com/questions/26597116/)

**Comment by erdogant** [comment]
I see. Well once upon a time there was an issue (not pca but another) that plots were not visible when using the plot functionality. I then used `plt.show()` in the code to force it. Maybe this was a bug that is fixed. I can remove the `plt.show` because I do not see a reason to do it either. I will keep the `fig.set_visible(visible)` or do you suggest an alternative?

**Comment by erdogant** [comment]
I created a [new version](https://github.com/erdogant/pca/releases/tag/2.0.3) where I removed `plt.show()`

pip install -U pca

**Comment by erdogant** [comment]
Closing this issue as it is fixed :)
