### ISSUE TITLE
Outlier detection plots

### ISSUE THREAD

**Issue by alexjj** [erdogant/pca#5]
Great library, thanks for sharing! Building all the plots is very convenient :)

This is a feature request to add plots that are useful for outlier detection:

* SPE/DmodX score vs row scatter with DCrit shown for moderate outliers
* Hotelling’s T^2 on the scores plot for strong outliers

For Hotelling’s this [SO post](https://stackoverflow.com/a/52339626) has one way.

**Comment by erdogant** [comment]
Great suggestion! The outlier detection is now available in the new version and an example can be found in the readme file.
The current implementation can rank outliers and therefore I'm not sure what the additional benefit is from using SPE/DmodX scores?

update with:
`pip install -U pca`

**Comment by alexjj** [comment]
Awesome!

I've only recently started learning about PCA but my understanding was the Hotelling's T2 was for strong outliers - i.e. those that significantly impact the PCs. Whereas DmodX is for moderate outliers, i.e. ones which are more like a temporary excursion from the model. 

Both outliers are important but could be treated differently. Strong ones may be removed from the model before fitting and moderate ones are deviations to keep but investigate further.

**Comment by erdogant** [comment]
I included SPE/dmodX in the library. See the readme file for some examples. Note that some of the input parameters are changed which allows to separately include spe/dmodx and hotelling t2 test outliers in the figures.

`pip install -U pca`

`model.biplot(legend=True, SPE=True, hotellingt2=True)`
